-- Riverhog PostgreSQL v1 fixture for the current unreleased v1 contract.
CREATE TABLE state_schema_revision (version_num VARCHAR(32) NOT NULL PRIMARY KEY);
INSERT INTO state_schema_revision (version_num) VALUES ('v1_0001');
CREATE TABLE app_keys (
	id VARCHAR NOT NULL,
	app VARCHAR NOT NULL,
	token_sha256 VARCHAR(64) NOT NULL,
	monthly_download_quota_bytes BIGINT,
	created_at VARCHAR NOT NULL,
	expires_at VARCHAR,
	revoked_at VARCHAR,
	last_used_at VARCHAR,
	PRIMARY KEY (id)
);
CREATE TABLE archive_download_usage (
	store VARCHAR NOT NULL,
	month_started_at VARCHAR NOT NULL,
	accounted_bytes BIGINT NOT NULL,
	updated_at VARCHAR NOT NULL,
	PRIMARY KEY (store)
);
CREATE TABLE catalog_events (
	sequence SERIAL NOT NULL,
	change VARCHAR NOT NULL,
	collection_id BIGINT NOT NULL,
	occurred_at VARCHAR NOT NULL,
	record_etag VARCHAR(64) NOT NULL,
	PRIMARY KEY (sequence)
);
CREATE TABLE collection_deletions (
	collection_id BIGSERIAL NOT NULL,
	challenge VARCHAR NOT NULL,
	plan_json TEXT NOT NULL,
	started_at VARCHAR NOT NULL,
	PRIMARY KEY (collection_id)
);
CREATE TABLE collection_uploads (
	collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	idempotency_key VARCHAR NOT NULL,
	ingest_source VARCHAR,
	initiated_by_app VARCHAR NOT NULL,
	initiated_by_key_id VARCHAR,
	event_context_json TEXT,
	state VARCHAR NOT NULL,
	archive_store VARCHAR NOT NULL,
	opened_at VARCHAR NOT NULL,
	last_activity_at VARCHAR NOT NULL,
	closed_at VARCHAR,
	archive_phase VARCHAR NOT NULL,
	archive_phase_updated_at VARCHAR NOT NULL,
	archive_attempt_count INTEGER NOT NULL,
	archive_next_attempt_at VARCHAR,
	archive_last_attempt_at VARCHAR,
	archive_failure VARCHAR,
	archive_storage_prefix VARCHAR NOT NULL,
	collection_manifest_bytes_b64 VARCHAR,
	collection_manifest_proof_bytes_b64 VARCHAR,
	planner_checkpoint_json TEXT NOT NULL,
	PRIMARY KEY (collection_id)
);
CREATE TABLE collections (
	id BIGSERIAL NOT NULL,
	creation_idempotency_key VARCHAR NOT NULL,
	content_etag VARCHAR(64) NOT NULL,
	record_etag VARCHAR(64) NOT NULL,
	metadata_revision BIGINT NOT NULL,
	metadata_updated_at VARCHAR NOT NULL,
	ingest_source VARCHAR,
	created_by_app VARCHAR NOT NULL,
	created_by_key_id VARCHAR,
	created_at VARCHAR NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_collections_application_idempotency_key UNIQUE (created_by_app, creation_idempotency_key)
);
CREATE TABLE lifecycle_events (
	sequence SERIAL NOT NULL,
	event_id VARCHAR NOT NULL,
	owner_app VARCHAR NOT NULL,
	subject VARCHAR,
	event_json TEXT NOT NULL,
	context_json TEXT,
	context_expires_at VARCHAR,
	PRIMARY KEY (sequence),
	UNIQUE (event_id)
);
CREATE TABLE retrieval_jobs (
	id VARCHAR NOT NULL,
	app VARCHAR NOT NULL,
	initiated_by_key_id VARCHAR,
	event_context_json TEXT,
	state VARCHAR NOT NULL,
	plan_etag VARCHAR(64) NOT NULL,
	constraints_json TEXT NOT NULL,
	created_at VARCHAR NOT NULL,
	requested_at VARCHAR,
	restore_requested_at VARCHAR,
	ready_at VARCHAR,
	expires_at VARCHAR,
	next_poll_at VARCHAR,
	completed_at VARCHAR,
	canceled_at VARCHAR,
	failure TEXT,
	PRIMARY KEY (id)
);
CREATE TABLE tags (
	id VARCHAR NOT NULL,
	created_by_app VARCHAR NOT NULL,
	created_by_key_id VARCHAR,
	created_at VARCHAR NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE app_key_access_grants (
	key_id VARCHAR NOT NULL,
	permission VARCHAR NOT NULL,
	resource VARCHAR NOT NULL,
	created_at VARCHAR NOT NULL,
	PRIMARY KEY (key_id, permission, resource),
	FOREIGN KEY(key_id) REFERENCES app_keys (id) ON DELETE CASCADE
);
CREATE TABLE archive_download_reservations (
	id VARCHAR NOT NULL,
	store VARCHAR NOT NULL,
	month_started_at VARCHAR NOT NULL,
	reserved_bytes BIGINT NOT NULL,
	created_at VARCHAR NOT NULL,
	expires_at VARCHAR NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(store) REFERENCES archive_download_usage (store) ON DELETE CASCADE
);
CREATE TABLE catalog_event_tags (
	sequence INTEGER NOT NULL,
	phase VARCHAR NOT NULL,
	tag_id VARCHAR NOT NULL,
	PRIMARY KEY (sequence, phase, tag_id),
	FOREIGN KEY(sequence) REFERENCES catalog_events (sequence) ON DELETE CASCADE,
	CONSTRAINT ck_catalog_event_tags_phase CHECK (phase IN ('before', 'after'))
);
CREATE TABLE collection_archive_copies (
	collection_id BIGINT NOT NULL,
	store VARCHAR NOT NULL,
	state VARCHAR NOT NULL,
	archive_storage_prefix VARCHAR,
	backend VARCHAR,
	storage_class VARCHAR,
	last_uploaded_at VARCHAR,
	last_verified_at VARCHAR,
	failure VARCHAR,
	PRIMARY KEY (collection_id, store),
	FOREIGN KEY(collection_id) REFERENCES collections (id) ON DELETE CASCADE
);
CREATE TABLE collection_archive_object_uploads (
	collection_id BIGINT NOT NULL,
	object_id VARCHAR NOT NULL,
	sequence INTEGER NOT NULL,
	kind VARCHAR NOT NULL,
	relative_path VARCHAR NOT NULL,
	object_path VARCHAR NOT NULL,
	plaintext_bytes BIGINT NOT NULL,
	source_bytes BIGINT NOT NULL,
	unit_plaintext_bytes BIGINT NOT NULL,
	plan_json TEXT NOT NULL,
	plan_sha256 VARCHAR(64) NOT NULL,
	state VARCHAR NOT NULL,
	checkpoint_json TEXT,
	sealed_receipt_json TEXT,
	failure TEXT,
	uploaded_bytes BIGINT NOT NULL,
	uploaded_parts INTEGER NOT NULL,
	total_parts INTEGER NOT NULL,
	updated_at VARCHAR NOT NULL,
	sealed_at VARCHAR,
	PRIMARY KEY (collection_id, object_id),
	FOREIGN KEY(collection_id) REFERENCES collection_uploads (collection_id) ON DELETE CASCADE
);
CREATE TABLE collection_files (
	collection_id BIGINT NOT NULL,
	path VARCHAR NOT NULL,
	bytes BIGINT NOT NULL,
	sha256 VARCHAR(64) NOT NULL,
	PRIMARY KEY (collection_id, path),
	FOREIGN KEY(collection_id) REFERENCES collections (id) ON DELETE CASCADE
);
CREATE TABLE collection_tags (
	collection_id BIGINT NOT NULL,
	tag_id VARCHAR NOT NULL,
	assigned_by_app VARCHAR NOT NULL,
	assigned_by_key_id VARCHAR,
	assigned_at VARCHAR NOT NULL,
	PRIMARY KEY (collection_id, tag_id),
	FOREIGN KEY(collection_id) REFERENCES collections (id) ON DELETE CASCADE,
	FOREIGN KEY(tag_id) REFERENCES tags (id) ON DELETE RESTRICT
);
CREATE TABLE collection_upload_files (
	collection_id BIGINT NOT NULL,
	path VARCHAR NOT NULL,
	file_order INTEGER NOT NULL,
	bytes BIGINT NOT NULL,
	sha256 VARCHAR(64) NOT NULL,
	raw_part_plaintext_bytes BIGINT,
	raw_digest_manifest_json TEXT,
	PRIMARY KEY (collection_id, path),
	FOREIGN KEY(collection_id) REFERENCES collection_uploads (collection_id) ON DELETE CASCADE
);
CREATE TABLE collection_upload_tags (
	collection_id BIGINT NOT NULL,
	tag_id VARCHAR NOT NULL,
	PRIMARY KEY (collection_id, tag_id),
	FOREIGN KEY(collection_id) REFERENCES collection_uploads (collection_id) ON DELETE CASCADE,
	FOREIGN KEY(tag_id) REFERENCES tags (id) ON DELETE RESTRICT
);
CREATE TABLE key_download_reservations (
	id VARCHAR NOT NULL,
	key_id VARCHAR NOT NULL,
	job_id VARCHAR NOT NULL,
	kind VARCHAR NOT NULL,
	month_started_at VARCHAR NOT NULL,
	reserved_bytes BIGINT NOT NULL,
	created_at VARCHAR NOT NULL,
	expires_at VARCHAR NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(key_id) REFERENCES app_keys (id) ON DELETE CASCADE
);
CREATE TABLE key_download_usage (
	key_id VARCHAR NOT NULL,
	month_started_at VARCHAR NOT NULL,
	accounted_bytes BIGINT NOT NULL,
	updated_at VARCHAR NOT NULL,
	PRIMARY KEY (key_id),
	FOREIGN KEY(key_id) REFERENCES app_keys (id) ON DELETE CASCADE
);
CREATE TABLE archive_copy_jobs (
	collection_id BIGINT NOT NULL,
	destination_store VARCHAR NOT NULL,
	destination_storage_prefix VARCHAR NOT NULL,
	source_store VARCHAR NOT NULL,
	initiated_by_app VARCHAR NOT NULL,
	initiated_by_key_id VARCHAR,
	event_context_json TEXT,
	state VARCHAR NOT NULL,
	requested_at VARCHAR NOT NULL,
	read_requested_at VARCHAR,
	ready_at VARCHAR,
	expires_at VARCHAR,
	next_attempt_at VARCHAR,
	completed_at VARCHAR,
	failure VARCHAR,
	PRIMARY KEY (collection_id, destination_store),
	FOREIGN KEY(collection_id, source_store) REFERENCES collection_archive_copies (collection_id, store) ON DELETE CASCADE
);
CREATE TABLE archive_copy_retirements (
	collection_id BIGINT NOT NULL,
	store VARCHAR NOT NULL,
	challenge VARCHAR NOT NULL,
	plan_json TEXT NOT NULL,
	started_at VARCHAR NOT NULL,
	PRIMARY KEY (collection_id, store),
	FOREIGN KEY(collection_id, store) REFERENCES collection_archive_copies (collection_id, store) ON DELETE CASCADE
);
CREATE TABLE collection_archive_attestations (
	collection_id BIGINT NOT NULL,
	store VARCHAR NOT NULL,
	state VARCHAR NOT NULL,
	attempt_count INTEGER NOT NULL,
	next_attempt_at VARCHAR NOT NULL,
	last_attempt_at VARCHAR,
	published_at VARCHAR,
	matured_at VARCHAR,
	failure TEXT,
	PRIMARY KEY (collection_id, store),
	FOREIGN KEY(collection_id, store) REFERENCES collection_archive_copies (collection_id, store) ON DELETE CASCADE
);
CREATE TABLE collection_archive_objects (
	collection_id BIGINT NOT NULL,
	store VARCHAR NOT NULL,
	object_id VARCHAR NOT NULL,
	object_order INTEGER NOT NULL,
	kind VARCHAR NOT NULL,
	object_path VARCHAR NOT NULL,
	plaintext_bytes BIGINT NOT NULL,
	stored_bytes BIGINT NOT NULL,
	sha256 VARCHAR(64),
	stored_sha256 VARCHAR(64),
	version_id VARCHAR,
	age_state_json TEXT,
	part_receipts_json TEXT,
	plan_sha256 VARCHAR(64),
	index_sha256 VARCHAR(64),
	backend VARCHAR NOT NULL,
	storage_class VARCHAR NOT NULL,
	uploaded_at VARCHAR NOT NULL,
	verified_at VARCHAR,
	PRIMARY KEY (collection_id, store, object_id),
	FOREIGN KEY(collection_id, store) REFERENCES collection_archive_copies (collection_id, store) ON DELETE CASCADE
);
CREATE TABLE collection_metadata_publications (
	collection_id BIGINT NOT NULL,
	store VARCHAR NOT NULL,
	desired_revision BIGINT NOT NULL,
	published_revision BIGINT,
	state VARCHAR NOT NULL,
	attempt_count INTEGER NOT NULL,
	next_attempt_at VARCHAR NOT NULL,
	last_attempt_at VARCHAR,
	failure TEXT,
	object_path VARCHAR,
	version_id VARCHAR,
	stored_bytes BIGINT,
	stored_sha256 VARCHAR(64),
	published_at VARCHAR,
	PRIMARY KEY (collection_id, store),
	FOREIGN KEY(collection_id, store) REFERENCES collection_archive_copies (collection_id, store) ON DELETE CASCADE
);
CREATE TABLE collection_proof_maturations (
	collection_id BIGINT NOT NULL,
	store VARCHAR NOT NULL,
	state VARCHAR NOT NULL,
	attempt_count INTEGER NOT NULL,
	next_attempt_at VARCHAR NOT NULL,
	last_attempt_at VARCHAR,
	matured_at VARCHAR,
	failure TEXT,
	PRIMARY KEY (collection_id, store),
	FOREIGN KEY(collection_id, store) REFERENCES collection_archive_copies (collection_id, store) ON DELETE CASCADE
);
CREATE TABLE retrieval_job_files (
	job_id VARCHAR NOT NULL,
	collection_id BIGINT NOT NULL,
	path VARCHAR NOT NULL,
	file_order INTEGER NOT NULL,
	PRIMARY KEY (job_id, collection_id, path),
	FOREIGN KEY(job_id) REFERENCES retrieval_jobs (id) ON DELETE CASCADE,
	FOREIGN KEY(collection_id, path) REFERENCES collection_files (collection_id, path)
);
CREATE TABLE archive_copy_object_uploads (
	collection_id BIGINT NOT NULL,
	destination_store VARCHAR NOT NULL,
	object_id VARCHAR NOT NULL,
	kind VARCHAR NOT NULL,
	object_path VARCHAR NOT NULL,
	plaintext_bytes BIGINT NOT NULL,
	sha256 VARCHAR(64),
	multipart_upload_id VARCHAR,
	multipart_content_length BIGINT,
	multipart_parts_json VARCHAR,
	uploaded_bytes BIGINT NOT NULL,
	uploaded_parts INTEGER NOT NULL,
	total_parts INTEGER NOT NULL,
	PRIMARY KEY (collection_id, destination_store, object_id),
	FOREIGN KEY(collection_id, destination_store) REFERENCES archive_copy_jobs (collection_id, destination_store) ON DELETE CASCADE
);
CREATE TABLE collection_archive_file_objects (
	collection_id BIGINT NOT NULL,
	store VARCHAR NOT NULL,
	path VARCHAR NOT NULL,
	sequence INTEGER NOT NULL,
	object_id VARCHAR NOT NULL,
	file_offset BIGINT NOT NULL,
	object_offset BIGINT NOT NULL,
	bytes BIGINT NOT NULL,
	member VARCHAR,
	PRIMARY KEY (collection_id, store, path, sequence),
	FOREIGN KEY(collection_id, store, object_id) REFERENCES collection_archive_objects (collection_id, store, object_id) ON DELETE CASCADE,
	FOREIGN KEY(collection_id, path) REFERENCES collection_files (collection_id, path) ON DELETE CASCADE
);
CREATE TABLE retrieval_cache_objects (
	source_store VARCHAR NOT NULL,
	collection_id BIGINT NOT NULL,
	object_id VARCHAR NOT NULL,
	object_path VARCHAR NOT NULL,
	version_id VARCHAR,
	stored_bytes BIGINT NOT NULL,
	stored_sha256 VARCHAR(64) NOT NULL,
	cached_at VARCHAR NOT NULL,
	verified_at VARCHAR NOT NULL,
	state VARCHAR NOT NULL,
	PRIMARY KEY (source_store, collection_id, object_id),
	FOREIGN KEY(collection_id, source_store, object_id) REFERENCES collection_archive_objects (collection_id, store, object_id) ON DELETE CASCADE
);
CREATE TABLE retrieval_job_objects (
	job_id VARCHAR NOT NULL,
	collection_id BIGINT NOT NULL,
	source_store VARCHAR NOT NULL,
	object_id VARCHAR NOT NULL,
	object_order INTEGER NOT NULL,
	read_mode VARCHAR NOT NULL,
	PRIMARY KEY (job_id, collection_id, source_store, object_id),
	FOREIGN KEY(job_id) REFERENCES retrieval_jobs (id) ON DELETE CASCADE,
	FOREIGN KEY(collection_id, source_store, object_id) REFERENCES collection_archive_objects (collection_id, store, object_id)
);
CREATE TABLE retrieval_cache_leases (
	owner VARCHAR NOT NULL,
	source_store VARCHAR NOT NULL,
	collection_id BIGINT NOT NULL,
	object_id VARCHAR NOT NULL,
	expires_at VARCHAR NOT NULL,
	PRIMARY KEY (owner, source_store, collection_id, object_id),
	FOREIGN KEY(source_store, collection_id, object_id) REFERENCES retrieval_cache_objects (source_store, collection_id, object_id) ON DELETE CASCADE
);
CREATE INDEX ix_app_keys_app ON app_keys (app, id);
CREATE UNIQUE INDEX ux_app_keys_token_sha256 ON app_keys (token_sha256);
CREATE INDEX ix_catalog_events_collection ON catalog_events (collection_id, sequence);
CREATE UNIQUE INDEX ux_collection_uploads_application_idempotency_key ON collection_uploads (initiated_by_app, idempotency_key);
CREATE INDEX ix_lifecycle_events_context_expiry ON lifecycle_events (context_expires_at);
CREATE INDEX ix_lifecycle_events_owner_sequence ON lifecycle_events (owner_app, sequence);
CREATE INDEX ix_lifecycle_events_owner_subject_context ON lifecycle_events (owner_app, subject, context_expires_at);
CREATE INDEX ix_retrieval_jobs_due ON retrieval_jobs (state, next_poll_at, id);
CREATE INDEX ix_app_key_access_grants_permission ON app_key_access_grants (permission, resource, key_id);
CREATE INDEX ix_app_key_access_grants_resource ON app_key_access_grants (resource, permission, key_id);
CREATE INDEX ix_archive_download_reservations_expiry ON archive_download_reservations (store, expires_at);
CREATE INDEX ix_catalog_event_tags_visibility ON catalog_event_tags (phase, tag_id, sequence);
CREATE UNIQUE INDEX ux_collection_archive_object_uploads_sequence ON collection_archive_object_uploads (collection_id, sequence);
CREATE INDEX ix_collection_tags_tag ON collection_tags (tag_id, collection_id);
CREATE INDEX idx_collection_upload_files_collection_order ON collection_upload_files (collection_id, file_order);
CREATE UNIQUE INDEX ux_collection_upload_files_order ON collection_upload_files (collection_id, file_order);
CREATE INDEX ix_collection_upload_tags_tag ON collection_upload_tags (tag_id, collection_id);
CREATE INDEX ix_key_download_reservations_expiry ON key_download_reservations (expires_at, key_id);
CREATE INDEX ix_key_download_reservations_job ON key_download_reservations (job_id, kind);
CREATE INDEX ix_key_download_reservations_key_month ON key_download_reservations (key_id, month_started_at);
CREATE INDEX ix_archive_copy_jobs_due ON archive_copy_jobs (state, next_attempt_at, requested_at);
CREATE INDEX ix_collection_archive_attestations_due ON collection_archive_attestations (state, next_attempt_at, collection_id, store);
CREATE INDEX idx_collection_archive_objects_order ON collection_archive_objects (collection_id, store, object_order);
CREATE INDEX ix_collection_metadata_publications_due ON collection_metadata_publications (state, next_attempt_at, collection_id, store);
CREATE INDEX ix_collection_proof_maturations_due ON collection_proof_maturations (state, next_attempt_at, collection_id, store);
CREATE INDEX ix_retrieval_job_files_order ON retrieval_job_files (job_id, file_order);
CREATE INDEX idx_collection_archive_file_objects_object ON collection_archive_file_objects (collection_id, store, object_id);
CREATE INDEX ix_retrieval_cache_objects_cleanup ON retrieval_cache_objects (state, cached_at);
CREATE INDEX ix_retrieval_job_objects_order ON retrieval_job_objects (job_id, object_order);
CREATE INDEX ix_retrieval_cache_leases_expiry ON retrieval_cache_leases (expires_at, owner);
INSERT INTO app_keys (
    id, app, token_sha256, monthly_download_quota_bytes, created_at
) VALUES (
    'fixture-key',
    'fixture-client',
    '9bb667f30707b8e3c2d372db3ab5bee247813f3d2fa86cf86a5640d19bec48f6',
    1048576,
    '2026-01-01T00:00:00.000000Z'
);
INSERT INTO app_key_access_grants (key_id, permission, resource, created_at)
VALUES ('fixture-key', 'catalog:read', '*', '2026-01-01T00:00:00.000000Z');
INSERT INTO collections (
    id, creation_idempotency_key, content_etag, record_etag, metadata_revision,
    metadata_updated_at, ingest_source, created_by_app, created_by_key_id, created_at
) VALUES (
    1, 'fixture-collection',
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    1, '2026-01-01T00:00:00.000000Z', 'fixture', 'fixture-client', 'fixture-key',
    '2026-01-01T00:00:00.000000Z'
);
INSERT INTO collection_files (collection_id, path, bytes, sha256)
VALUES (1, 'notes/fixture.txt', 12, '5cb72f90e968922d30557d0af8f719d21f61792becaa87eb32477767d739dc0b');
INSERT INTO collection_archive_copies (
    collection_id, store, state, archive_storage_prefix, backend, storage_class,
    last_uploaded_at, last_verified_at
) VALUES (
    1, 'fixture-archive', 'uploaded', 'archives/fixture-archive-id', 's3', 'STANDARD',
    '2026-01-01T00:00:00.000000Z', '2026-01-01T00:00:00.000000Z'
);
INSERT INTO collection_archive_objects (
    collection_id, store, object_id, object_order, kind, object_path,
    plaintext_bytes, stored_bytes, sha256, stored_sha256, version_id,
    age_state_json, part_receipts_json, plan_sha256, index_sha256,
    backend, storage_class, uploaded_at, verified_at
) VALUES (
    1, 'fixture-archive', 'segment-000000000000', 0, 'segment',
    'archives/fixture-archive-id/volumes/segment-000000000000.age',
    12, 193, NULL, NULL, 'fixture-version',
    '{"format":"age-v1-scrypt-resumable","header_b64":"YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNjcnlwdCBBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnIDEKNjEyMGp3bzZEMGtEbXltOXMrdkNRcWNibnQ4bkc0U3kzMUlIbko3SExNRQotLS0gWDRWN2kwSnNmejZjaUNPTlVES2ZvUzdtTFdGMmc0aWx3V0x3Qm9acVZYQQo","payload_nonce_b64":"AwMDAwMDAwMDAwMDAwMDAw","plaintext_size":12}', '[{"etag":"e475137133e22134d3410b682f082ae214768f3caf8607519ef6702691caeca5","number":1,"plaintext_bytes":12,"plaintext_sha256":"5cb72f90e968922d30557d0af8f719d21f61792becaa87eb32477767d739dc0b","plaintext_start":0,"stored_bytes":193,"stored_sha256":"e475137133e22134d3410b682f082ae214768f3caf8607519ef6702691caeca5"}]',
    'a78a447154425433f992bd67e82acdbfe7aa8636fa5fda2403e86c193304c920', NULL, 's3', 'STANDARD',
    '2026-01-01T00:00:00.000000Z', '2026-01-01T00:00:00.000000Z'
);
INSERT INTO collection_archive_file_objects (
    collection_id, store, path, sequence, object_id, file_offset, object_offset, bytes, member
) VALUES (
    1, 'fixture-archive', 'notes/fixture.txt', 0, 'segment-000000000000',
    0, 0, 12, NULL
);
INSERT INTO retrieval_jobs (
    id, app, initiated_by_key_id, state, plan_etag, constraints_json,
    created_at, requested_at, next_poll_at
) VALUES (
    'fixture-retrieval', 'fixture-client', 'fixture-key', 'requested',
    'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
    '{"etag":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc","files":[{"bytes":12,"collection_id":1,"path":"notes/fixture.txt","sha256":"5cb72f90e968922d30557d0af8f719d21f61792becaa87eb32477767d739dc0b"}],"format":"riverhog-retrieval-plan/v1","lease_seconds":3600,"objects":[{"collection_id":1,"object_id":"segment-000000000000","read_mode":"restore_required","source_store":"fixture-archive"}]}',
    '2026-01-01T00:00:00.000000Z', '2026-01-01T00:00:00.000000Z',
    '2026-01-01T00:00:00.000000Z'
);
INSERT INTO retrieval_job_files (job_id, collection_id, path, file_order)
VALUES ('fixture-retrieval', 1, 'notes/fixture.txt', 0);
INSERT INTO retrieval_job_objects (
    job_id, collection_id, source_store, object_id, object_order, read_mode
) VALUES (
    'fixture-retrieval', 1, 'fixture-archive', 'segment-000000000000', 0,
    'restore_required'
);
INSERT INTO retrieval_cache_objects (
    source_store, collection_id, object_id, object_path, version_id, stored_bytes,
    stored_sha256, cached_at, verified_at, state
) VALUES (
    'fixture-archive', 1, 'segment-000000000000',
    'cache/fixture-archive/1/segment-000000000000', 'fixture-cache-version',
    193, 'e475137133e22134d3410b682f082ae214768f3caf8607519ef6702691caeca5',
    '2026-01-01T00:00:00.000000Z', '2026-01-01T00:00:00.000000Z', 'ready'
);
INSERT INTO retrieval_cache_leases (
    owner, source_store, collection_id, object_id, expires_at
) VALUES (
    'fixture-job', 'fixture-archive', 1, 'segment-000000000000',
    '2026-02-01T00:00:00.000000Z'
);
INSERT INTO lifecycle_events (
    sequence, event_id, owner_app, subject, event_json, context_json
) VALUES (
    1, 'riverhog-v1-event', 'fixture-client', '1',
    '{"data":{"collection_id":1},"datacontenttype":"application/json","id":"riverhog-v1-event","source":"urn:fixture:riverhog","specversion":"1.0","subject":"1","time":"2026-01-01T00:00:00.000000Z","type":"io.riverhog.riverhog.collection.finalized"}',
    '{"workflow":"fixture"}'
);
SELECT setval(pg_get_serial_sequence('collections', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('lifecycle_events', 'sequence'), 1, true);
