version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    assignees:
      - nashspence
    commit-message:
      prefix: deps
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    assignees:
      - nashspence
    commit-message:
      prefix: deps
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /companions/jeb/server
      - /companions/munchy/server
      - /companions/munchy/server/targets/av1-nvenc
      - /riverhog/server
      - /tests
      - /utilities/mango-fish
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    assignees:
      - nashspence
    commit-message:
      prefix: deps
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
