version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    assignees:
      - nashspence
    commit-message:
      prefix: deps
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    assignees:
      - nashspence
    commit-message:
      prefix: deps
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /companions/stove0/extensions
      - /companions/stove0/extensions/nvenc
      - /companions/stove0/server
      - /riverhog/adapters
      - /riverhog/server
      - /tests
      - /utilities/mango-fish
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    assignees:
      - nashspence
    commit-message:
      prefix: deps
    ignore:
      - dependency-name: python
        versions:
          - ">= 3.13"
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
