from __future__ import annotations

from typing import Protocol

from arc_core.domain.models import FetchSummary
from arc_core.domain.types import EntryId, FetchId, TargetStr


class FetchStore(Protocol):
    def find_reusable_fetch(self, target: TargetStr) -> FetchSummary | None: ...
    def create_fetch(self, target: TargetStr, entries: list[object], copies: list[object]) -> FetchSummary: ...
    def get_fetch(self, fetch_id: FetchId) -> FetchSummary: ...
    def get_manifest(self, fetch_id: FetchId) -> object: ...
    def accept_uploaded_entry(self, fetch_id: FetchId, entry_id: EntryId, sha256: str, content: bytes) -> object: ...
    def can_complete(self, fetch_id: FetchId) -> bool: ...
    def mark_verifying(self, fetch_id: FetchId) -> None: ...
    def mark_done(self, fetch_id: FetchId) -> None: ...
    def mark_failed(self, fetch_id: FetchId, reason: str) -> None: ...
