from __future__ import annotations

from typing import Protocol

from arc_core.domain.types import CollectionId, Sha256Hex


class HotStore(Protocol):
    def materialize_closed_collection(self, collection_id: CollectionId) -> None: ...
    def has_file(self, collection_id: CollectionId, path: str) -> bool: ...
    def put_file(self, sha256: Sha256Hex, content: bytes) -> None: ...
    def hot_bytes_for_collection(self, collection_id: CollectionId) -> int: ...
