from __future__ import annotations

from typing import Protocol


class HotStore(Protocol):
    def put_collection_file(self, collection_id: str, path: str, content: bytes) -> None: ...
    def get_collection_file(self, collection_id: str, path: str) -> bytes: ...
    def has_collection_file(self, collection_id: str, path: str) -> bool: ...
    def delete_collection_file(self, collection_id: str, path: str) -> None: ...
    def list_collection_files(self, collection_id: str) -> list[tuple[str, int]]: ...
