from __future__ import annotations

from typing import Protocol


class UploadStore(Protocol):
    def create_upload(self, target_path: str, length: int) -> str: ...
    def get_offset(self, tus_url: str) -> int: ...
    def append_upload_chunk(
        self,
        tus_url: str,
        *,
        offset: int,
        checksum: str,
        content: bytes,
    ) -> tuple[int, str | None]: ...
    def read_target(self, target_path: str) -> bytes: ...
    def delete_target(self, target_path: str) -> None: ...
    def cancel_upload(self, tus_url: str) -> None: ...
