from __future__ import annotations

import shlex
import stat
from collections.abc import Mapping
from dataclasses import dataclass
from os import PathLike
from pathlib import Path
from typing import Any

from riverhog_core.config_yaml import ConfigError, load_yaml_config, validate_json_schema

DEFAULT_MARKER_NAME = ".riverhog.mount-marker"
DEFAULT_ROUTES_FILENAME = "mount-marker-routes.yaml"
GENERATED_HEADER = "# Generated by Riverhog mount markers; do not edit."

MOUNT_MARKER_ROUTES_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "schema_version": {"type": "integer", "const": 1},
        "kind": {"type": "string", "const": "riverhog.mount_marker_routes"},
        "routes": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "enabled": {"type": "boolean"},
                    "script": {"type": "string", "minLength": 1},
                    "args": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": ["script"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["routes"],
    "additionalProperties": False,
}

PathInput = str | PathLike[str]


@dataclass(frozen=True)
class MountMarkerAction:
    marker: str
    script: str
    args: tuple[str, ...] = ()


def default_routes_file(config_dir: PathInput, *, filename: str = DEFAULT_ROUTES_FILENAME) -> Path:
    return Path(config_dir).expanduser().resolve().parent / filename


def _validate_script_name(script_name: str) -> None:
    if not script_name or "/" in script_name or script_name in {".", ".."}:
        raise ConfigError(f"invalid mount marker route script: {script_name!r}")


def _validate_marker_route(marker_route: str) -> None:
    if not marker_route or "/" in marker_route or marker_route in {".", ".."}:
        raise ConfigError(f"invalid mount marker route: {marker_route!r}")


def _route_args(route_name: str, route: Mapping[str, Any]) -> tuple[str, ...]:
    raw_args = route.get("args", [])
    if raw_args is None:
        return ()
    if not isinstance(raw_args, list):
        raise ConfigError(f"mount marker route {route_name!r}.args must be a list")
    return tuple(str(arg) for arg in raw_args)


def load_mount_marker_actions(config_file: PathInput) -> list[MountMarkerAction]:
    path = Path(config_file).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"mount marker route config not found: {path}")

    raw = load_yaml_config(path)
    validate_json_schema(raw, MOUNT_MARKER_ROUTES_SCHEMA, label=str(path))
    routes = raw.get("routes")
    if not isinstance(routes, Mapping):
        raise ConfigError(f"{path}.routes must be a mapping")

    actions: list[MountMarkerAction] = []
    for raw_marker, raw_route in routes.items():
        marker = str(raw_marker).strip()
        if not isinstance(raw_route, Mapping):
            raise ConfigError(f"mount marker route {marker!r} must be a mapping")
        if not bool(raw_route.get("enabled", True)):
            continue
        _validate_marker_route(marker)
        script = str(raw_route.get("script") or "").strip()
        _validate_script_name(script)
        actions.append(
            MountMarkerAction(
                marker=marker,
                script=script,
                args=_route_args(marker, raw_route),
            )
        )
    return actions


def _trigger_text(scripts_dir: Path, action: MountMarkerAction) -> str:
    script = scripts_dir / action.script
    script_args = " ".join(shlex.quote(arg) for arg in action.args)
    suffix = f" {script_args}" if script_args else ""
    quoted_script = shlex.quote(str(script))
    return "\n".join(
        [
            "#!/bin/sh",
            GENERATED_HEADER,
            "set -eu",
            'if [ "$#" -ne 1 ]; then',
            '    printf "usage: %s MOUNT_POINT\\n" "$0" >&2',
            "    exit 2",
            "fi",
            f"if [ ! -x {quoted_script} ]; then",
            f"    printf 'mount marker action is not executable: %s\\n' {quoted_script} >&2",
            "    exit 127",
            "fi",
            f'exec {quoted_script} "$1"{suffix}',
            "",
        ]
    )


def _remove_old_generated_triggers(dest_dir: Path) -> None:
    if not dest_dir.exists():
        return
    for path in dest_dir.iterdir():
        if not path.is_file():
            continue
        try:
            first_lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        if len(first_lines) >= 2 and first_lines[1] == GENERATED_HEADER:
            path.unlink()


def render_mount_marker_triggers(
    config_file: PathInput,
    dest_dir: PathInput,
    scripts_dir: PathInput,
) -> list[Path]:
    dest_path = Path(dest_dir).expanduser().resolve()
    scripts_path = Path(scripts_dir).expanduser().resolve()

    dest_path.mkdir(parents=True, exist_ok=True)
    _remove_old_generated_triggers(dest_path)

    written: list[Path] = []
    for action in load_mount_marker_actions(config_file):
        out = dest_path / action.marker
        out.write_text(_trigger_text(scripts_path, action), encoding="utf-8")
        mode = out.stat().st_mode
        out.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written.append(out)
    return written


def route_for_marker(config_file: PathInput, route_name: str) -> str:
    route_name = route_name.strip()
    routes = {action.marker: action for action in load_mount_marker_actions(config_file)}
    try:
        return routes[route_name].marker
    except KeyError as exc:
        available = ", ".join(sorted(routes)) or "none"
        raise ConfigError(
            f"mount marker route {route_name!r} is not configured (available: {available})"
        ) from exc


def write_mount_marker(
    config_file: PathInput,
    route_name: str,
    mount_point: PathInput,
    *,
    marker_name: str = DEFAULT_MARKER_NAME,
    force: bool = False,
) -> Path:
    _validate_marker_route(marker_name)
    marker_route = route_for_marker(config_file, route_name)
    root = Path(mount_point).expanduser().resolve()
    if not root.is_dir():
        raise NotADirectoryError(root)

    marker = root / marker_name
    text = f"{marker_route}\n"
    current = marker.read_text(encoding="utf-8", errors="replace") if marker.exists() else None
    if current is not None and current != text and not force:
        raise FileExistsError(f"marker already exists with different content: {marker}")
    marker.write_text(text, encoding="utf-8")
    return marker
