from __future__ import annotations

import shlex
import stat
from collections.abc import Mapping
from dataclasses import dataclass
from os import PathLike
from pathlib import Path
from typing import Any

from riverhog_core.config_yaml import ConfigError, load_yaml_config, validate_json_schema

DEFAULT_GOGURT_MARKER_NAME = ".gogurt"
DEFAULT_GOGURT_CONFIG_FILENAME = "gogurt-routes.yaml"
GOGURT_EMOJI = "🛹"
GENERATED_HEADER = "# Generated by Gogurt; do not edit."

GOGURT_ROUTES_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "schema_version": {"type": "integer", "const": 1},
        "kind": {"type": "string", "const": "gogurt.routes"},
        "routes": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "enabled": {"type": "boolean"},
                    "script": {"type": "string", "minLength": 1},
                    "args": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": ["script"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["routes"],
    "additionalProperties": False,
}

PathInput = str | PathLike[str]


@dataclass(frozen=True)
class GogurtAction:
    route: str
    script: str
    args: tuple[str, ...] = ()


def default_gogurt_config_file(
    config_dir: PathInput,
    *,
    filename: str = DEFAULT_GOGURT_CONFIG_FILENAME,
) -> Path:
    return Path(config_dir).expanduser().resolve().parent / filename


def _validate_gogurt_script_name(script_name: str) -> None:
    if not script_name or "/" in script_name or script_name in {".", ".."}:
        raise ConfigError(f"invalid gogurt route script: {script_name!r}")


def _validate_gogurt_route(route_name: str) -> None:
    if not route_name or "/" in route_name or route_name in {".", ".."}:
        raise ConfigError(f"invalid gogurt route: {route_name!r}")


def _validate_gogurt_marker_name(marker_name: str) -> None:
    if not marker_name or "/" in marker_name or marker_name in {".", ".."}:
        raise ConfigError(f"invalid gogurt marker name: {marker_name!r}")


def _route_args(route_name: str, route: Mapping[str, Any]) -> tuple[str, ...]:
    raw_args = route.get("args", [])
    if raw_args is None:
        return ()
    if not isinstance(raw_args, list):
        raise ConfigError(f"gogurt route {route_name!r}.args must be a list")
    return tuple(str(arg) for arg in raw_args)


def load_gogurt_actions(config_file: PathInput) -> list[GogurtAction]:
    path = Path(config_file).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"gogurt route config not found: {path}")

    raw = load_yaml_config(path)
    validate_json_schema(raw, GOGURT_ROUTES_SCHEMA, label=str(path))
    routes = raw.get("routes")
    if not isinstance(routes, Mapping):
        raise ConfigError(f"{path}.routes must be a mapping")

    actions: list[GogurtAction] = []
    for raw_route_name, raw_route in routes.items():
        route_name = str(raw_route_name).strip()
        if not isinstance(raw_route, Mapping):
            raise ConfigError(f"gogurt route {route_name!r} must be a mapping")
        if not bool(raw_route.get("enabled", True)):
            continue
        _validate_gogurt_route(route_name)
        script = str(raw_route.get("script") or "").strip()
        _validate_gogurt_script_name(script)
        actions.append(
            GogurtAction(
                route=route_name,
                script=script,
                args=_route_args(route_name, raw_route),
            )
        )
    return actions


def _trigger_text(scripts_dir: Path, action: GogurtAction) -> str:
    script = scripts_dir / action.script
    script_args = " ".join(shlex.quote(arg) for arg in action.args)
    suffix = f" {script_args}" if script_args else ""
    quoted_emoji = shlex.quote(GOGURT_EMOJI)
    quoted_route = shlex.quote(action.route)
    quoted_action = shlex.quote(action.script)
    quoted_script = shlex.quote(str(script))
    return "\n".join(
        [
            "#!/bin/sh",
            GENERATED_HEADER,
            "set -eu",
            'if [ "$#" -ne 1 ]; then',
            '    printf "usage: %s MOUNT_POINT\\n" "$0" >&2',
            "    exit 2",
            "fi",
            f"if [ ! -x {quoted_script} ]; then",
            f"    printf 'gogurt action is not executable: %s\\n' {quoted_script} >&2",
            "    exit 127",
            "fi",
            (
                f"printf '%s gogurt launch available: route=%s action=%s mount=%s\\n' "
                f'{quoted_emoji} {quoted_route} {quoted_action} "$1" >&2'
            ),
            'case "${GOGURT_AUTORUN:-}" in',
            "    1|true|TRUE|yes|YES|on|ON)",
            (
                f"        printf '%s gogurt autorun confirmed by GOGURT_AUTORUN\\n' "
                f"{quoted_emoji} >&2"
            ),
            "        ;;",
            "    *)",
            "        if [ -t 0 ]; then",
            f"            printf '%s gogurt run this action? [y/N] ' {quoted_emoji} >&2",
            "            read answer",
            '            case "$answer" in',
            "                y|Y|yes|YES|Yes)",
            "                    ;;",
            "                *)",
            (
                f"                    printf '%s gogurt launch declined: "
                f'route=%s mount=%s\\n\' {quoted_emoji} {quoted_route} "$1" >&2'
            ),
            "                    exit 0",
            "                    ;;",
            "            esac",
            "        else",
            (
                f"            printf '%s gogurt launch waiting for confirmation; "
                f"set GOGURT_AUTORUN=1 to allow noninteractive autorun.\\n' "
                f"{quoted_emoji} >&2"
            ),
            "            exit 0",
            "        fi",
            "        ;;",
            "esac",
            (
                f"printf '%s gogurt launching: route=%s action=%s mount=%s\\n' "
                f'{quoted_emoji} {quoted_route} {quoted_action} "$1" >&2'
            ),
            f'exec {quoted_script} "$1"{suffix}',
            "",
        ]
    )


def _remove_old_generated_triggers(dest_dir: Path) -> None:
    if not dest_dir.exists():
        return
    for path in dest_dir.iterdir():
        if not path.is_file():
            continue
        try:
            first_lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        if len(first_lines) >= 2 and first_lines[1] == GENERATED_HEADER:
            path.unlink()


def render_gogurt_triggers(
    config_file: PathInput,
    dest_dir: PathInput,
    scripts_dir: PathInput,
) -> list[Path]:
    dest_path = Path(dest_dir).expanduser().resolve()
    scripts_path = Path(scripts_dir).expanduser().resolve()

    dest_path.mkdir(parents=True, exist_ok=True)
    _remove_old_generated_triggers(dest_path)

    written: list[Path] = []
    for action in load_gogurt_actions(config_file):
        out = dest_path / action.route
        out.write_text(_trigger_text(scripts_path, action), encoding="utf-8")
        mode = out.stat().st_mode
        out.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written.append(out)
    return written


def route_for_gogurt_marker(config_file: PathInput, route_name: str) -> str:
    route_name = route_name.strip()
    routes = {action.route: action for action in load_gogurt_actions(config_file)}
    try:
        return routes[route_name].route
    except KeyError as exc:
        available = ", ".join(sorted(routes)) or "none"
        raise ConfigError(
            f"gogurt route {route_name!r} is not configured (available: {available})"
        ) from exc


def plan_gogurt_marker(
    config_file: PathInput,
    route_name: str,
    mount_point: PathInput,
    *,
    marker_name: str = DEFAULT_GOGURT_MARKER_NAME,
    force: bool = False,
) -> dict[str, object]:
    _validate_gogurt_marker_name(marker_name)
    marker_route = route_for_gogurt_marker(config_file, route_name)
    root = Path(mount_point).expanduser().resolve()
    if not root.is_dir():
        raise NotADirectoryError(root)

    marker = root / marker_name
    text = f"{marker_route}\n"
    current = marker.read_text(encoding="utf-8", errors="replace") if marker.exists() else None
    if current is not None and current != text and not force:
        raise FileExistsError(f"gogurt marker already exists with different content: {marker}")
    if current == text:
        status = "would_keep"
    elif current is not None:
        status = "would_replace"
    else:
        status = "would_write"
    return {
        "dry_run": True,
        "status": status,
        "route": marker_route,
        "mount_point": str(root),
        "marker": str(marker),
        "marker_name": marker_name,
        "content": text,
        "force": force,
        "exists": current is not None,
    }


def write_gogurt_marker(
    config_file: PathInput,
    route_name: str,
    mount_point: PathInput,
    *,
    marker_name: str = DEFAULT_GOGURT_MARKER_NAME,
    force: bool = False,
) -> Path:
    plan = plan_gogurt_marker(
        config_file,
        route_name,
        mount_point,
        marker_name=marker_name,
        force=force,
    )
    marker = Path(str(plan["marker"]))
    text = str(plan["content"])
    marker.write_text(text, encoding="utf-8")
    return marker
