from __future__ import annotations

from pathlib import Path

import yaml

from riverhog_api.app import create_app


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    document = create_app().openapi()
    output = yaml.safe_dump(
        document,
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    (root / "contracts" / "openapi" / "riverhog.v1.yaml").write_text(
        "# Generated by make openapi.\n" + output,
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
