from __future__ import annotations

from typing import BinaryIO, Protocol

from riverhog_core.domain.models import ImageSummary
from riverhog_core.domain.types import CollectionId, ImageId


class PlannerPort(Protocol):
    def include_collection(self, collection_id: CollectionId) -> None: ...
    def get_plan(self, **kwargs: object) -> object: ...
    def list_images(self, **kwargs: object) -> object: ...
    def get_image(self, image_id: ImageId) -> ImageSummary: ...
    def open_iso_stream(self, image_id: ImageId) -> BinaryIO: ...
